[tool.poetry]
name = "course-work-4"
version = "0.1.0"
description = ""
authors = ["MrKlasis <d23kv321@gmail.com>"]
readme = "README.md"
packages = [{include = "CW_4"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"